apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: hello-nginx
spec:
 replicas: 3 #escalar pods
 template:
  metadata:
   labels:
    app: hello-nginx-pod
  spec:
   containers:
    - name: nginx
      image: nginx:1.17-alpine
      ports:
      - containerPort: 80

      resources:
       requests:
        memory: "64Mi"
        cpu: "200m"
       limits:
        cpu: "250m"